from fastapi import APIRouter
from core.schemas import (
    HealthResponse,
    OrderInput,
    PredictionResponse,
    SellerBehaviorInput,
    SellerCategoryResponse,
    SellerRevenueInput,
)
from core.exceptions import ModelNotLoadedError
from core.predictor import DelayPredictor

predictor = DelayPredictor()

router = APIRouter()

@router.get(
    "/health",
    response_model=HealthResponse,
    tags=["Health"],
    summary="API Health Status",
    description="Returns the operational status of the API and checks if machine learning models are loaded and ready.",
)
async def health_check():
    return HealthResponse(
        status="ok",
        model_loaded=predictor.is_loaded,
        version="1.1.0",
    )

@router.post(
    "/predict",
    response_model=PredictionResponse,
    tags=["Prediction"],
    summary="Predict Delivery Delay",
    description="Predicts the number of days a delivery is likely to be delayed. Analysis shows that 33% of all bad reviews are caused by delays, with late orders dropping average scores from 4.29 to 2.46.",
)
async def predict_delay(order: OrderInput):
    if not predictor.is_loaded:
        raise ModelNotLoadedError("Model artifacts not loaded.")
    result = predictor.predict(order)
    return PredictionResponse(**result)

@router.post(
    "/predict_revenue_category",
    response_model=SellerCategoryResponse,
    tags=["Seller Categorization"],
    summary="Predict Seller Revenue Tier",
    description="Analyzes seller scale to segment them into 'Emerging' or 'High-Impact'. Note: 50% of marketplace revenue is generated by only 4% of sellers, making their retention mission-critical.",
)
async def predict_revenue_category(seller: SellerRevenueInput):
    if not predictor.is_loaded:
        raise ModelNotLoadedError("Model artifacts not loaded.")
    result = predictor.predict_revenue_category(seller)
    return SellerCategoryResponse(**result)

@router.post(
    "/predict_behavior_category",
    response_model=SellerCategoryResponse,
    tags=["Seller Categorization"],
    summary="Predict Seller Behavioral Category",
    description="Clusters sellers into 'Efficient', 'Premium', or 'Struggling' based on operational behavior (delivery speed, reliability, and reviews) without considering revenue scale.",
)
async def predict_behavior_category(seller: SellerBehaviorInput):
    if not predictor.is_loaded:
        raise ModelNotLoadedError("Model artifacts not loaded.")
    result = predictor.predict_behavior_category(seller)
    return SellerCategoryResponse(**result)
