
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field


class OrderInput(BaseModel):

    customer_state: str = Field(
        ...,
        min_length=2, max_length=2,
        description="Customer's Brazilian state code (e.g. 'SP', 'RJ').",
        examples=["SP"],
    )
    customer_city: str = Field(
        ...,
        description="Customer's city name.",
        examples=["sao paulo"],
    )
    customer_zip_code_prefix: int = Field(
        ...,
        description="First 5 digits of customer zip code.",
        examples=[1046],
    )
    seller_state: str = Field(
        ...,
        min_length=2, max_length=2,
        description="Seller's Brazilian state code (e.g. 'MG').",
        examples=["MG"],
    )
    seller_city: str = Field(
        ...,
        description="Seller's city name.",
        examples=["belo horizonte"],
    )
    seller_zip_code_prefix: int = Field(
        ...,
        description="First 5 digits of seller zip code.",
        examples=[30130],
    )
    order_size: int = Field(
        ...,
        ge=1,
        description="Number of items in the order.",
        examples=[2],
    )
    order_purchase_timestamp: datetime = Field(
        ...,
        description="Timestamp when the order was placed (ISO 8601).",
        examples=["2024-03-15T14:30:00"],
    )


class FeatureInfluence(BaseModel):
    """One feature's SHAP contribution to the prediction."""

    feature: str = Field(
        ...,
        description="Feature name.",
    )
    shap_value: float = Field(
        ...,
        description="SHAP value (positive pushes toward delay, negative toward early).",
    )
    direction: str = Field(
        ...,
        description="'increases delay' or 'decreases delay'.",
    )


class PredictionResponse(BaseModel):
    """Output schema – predicted delivery delay."""

    predicted_delay_days: float = Field(
        ...,
        description="Expected delay in days (positive = late, negative = early).",
    )
    delay_category: str = Field(
        ...,
        description="Human-readable delay category.",
    )
    confidence_note: str = Field(
        ...,
        description="A note about the prediction's context.",
    )
    top_features: List[FeatureInfluence] = Field(
        ...,
        description="Top features that most influenced this prediction, ranked by absolute SHAP value.",
    )


class HealthResponse(BaseModel):
    status: str
    model_loaded: bool
    version: str


class SellerRevenueInput(BaseModel):
    """Input schema - seller features required for revenue clustering."""

    total_revenue: float = Field(..., description="Total revenue generated by the seller.")
    total_orders: int = Field(..., description="Total number of orders.")
    avg_order_value: float = Field(..., description="Average value per order.")
    avg_delivery_time_days: float = Field(..., description="Average delivery time in days.")
    late_delivery_rate: float = Field(..., description="Ratio of late deliveries.")
    avg_freight_per_order: float = Field(..., description="Average freight cost per order.")
    avg_processing_time_days: float = Field(..., description="Average processing time in days.")
    avg_review_score: float = Field(..., description="Average customer review score.")
    review_count: int = Field(..., description="Total number of reviews.")


class SellerBehaviorInput(BaseModel):
    """Input schema - seller features required for behavior clustering."""

    avg_order_value: float = Field(..., description="Average value per order.")
    avg_delivery_time_days: float = Field(..., description="Average delivery time in days.")
    late_delivery_rate: float = Field(..., description="Ratio of late deliveries.")
    avg_freight_per_order: float = Field(..., description="Average freight cost per order.")
    avg_processing_time_days: float = Field(..., description="Average processing time in days.")
    avg_review_score: float = Field(..., description="Average customer review score.")


class SellerCategoryResponse(BaseModel):
    """Output schema - predicted seller category."""

    cluster_id: int = Field(
        ...,
        description="The assigned cluster ID.",
    )
    segment_name: str = Field(
        ...,
        description="Human-readable segment name.",
    )
