
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field


class OrderInput(BaseModel):
    """Input schema – all fields needed to predict delivery delay."""

    # ── Identifiers / lookup keys ────────────────────────────────────────
    seller_id: str = Field(
        ...,
        description="Unique seller identifier.",
        examples=["3442f8959a84dea7ee197c632cb2df15"],
    )
    customer_state: str = Field(
        ...,
        min_length=2, max_length=2,
        description="Customer's Brazilian state code (e.g. 'SP', 'RJ').",
        examples=["SP"],
    )
    customer_city: str = Field(
        ...,
        description="Customer's city name.",
        examples=["sao paulo"],
    )
    seller_state: str = Field(
        ...,
        min_length=2, max_length=2,
        description="Seller's Brazilian state code.",
        examples=["MG"],
    )
    seller_city: str = Field(
        ...,
        description="Seller's city name.",
        examples=["belo horizonte"],
    )
    product_category_name_english: Optional[str] = Field(
        None,
        description="English product category name (optional).",
        examples=["health_beauty"],
    )

    # ── Physical product properties ──────────────────────────────────────
    product_weight_g: float = Field(
        ..., ge=0,
        description="Product weight in grams.",
        examples=[500.0],
    )
    product_height_cm: float = Field(
        ..., ge=0,
        description="Product height in cm.",
        examples=[16.0],
    )
    product_width_cm: float = Field(
        ..., ge=0,
        description="Product width in cm.",
        examples=[11.0],
    )
    product_length_cm: float = Field(
        ..., ge=0,
        description="Product length in cm.",
        examples=[18.0],
    )

    # ── Order-level properties ───────────────────────────────────────────
    total_order_items: int = Field(
        ..., ge=1,
        description="Number of items in the order.",
        examples=[2],
    )
    freight_value: float = Field(
        ..., ge=0,
        description="Freight value for this item/order.",
        examples=[15.10],
    )
    price: float = Field(
        ..., ge=0,
        description="Product price.",
        examples=[59.90],
    )

    # ── Timestamps ───────────────────────────────────────────────────────
    order_purchase_timestamp: datetime = Field(
        ...,
        description="Timestamp when the order was placed (ISO 8601).",
        examples=["2024-03-15T14:30:00"],
    )
    order_estimated_delivery_date: datetime = Field(
        ...,
        description="Estimated delivery date given to the customer (ISO 8601).",
        examples=["2024-03-28T00:00:00"],
    )


class FeatureInfluence(BaseModel):
    """One feature's SHAP contribution to the prediction."""

    feature: str = Field(
        ...,
        description="Feature name.",
    )
    shap_value: float = Field(
        ...,
        description="SHAP value (positive pushes toward delay, negative toward early).",
    )
    direction: str = Field(
        ...,
        description="'increases delay' or 'decreases delay'.",
    )


class PredictionResponse(BaseModel):
    """Output schema – predicted delivery delay."""

    predicted_delay_days: float = Field(
        ...,
        description="Expected delay in days (positive = late, negative = early).",
    )
    delay_category: str = Field(
        ...,
        description="Human-readable delay category.",
    )
    confidence_note: str = Field(
        ...,
        description="A note about the prediction's context.",
    )
    top_features: List[FeatureInfluence] = Field(
        ...,
        description="Top features that most influenced this prediction, ranked by absolute SHAP value.",
    )


class HealthResponse(BaseModel):
    status: str
    model_loaded: bool
    version: str


class SellerRevenueInput(BaseModel):
    """Input schema - seller features required for revenue clustering."""

    total_revenue: float = Field(..., description="Total revenue generated by the seller.")
    total_orders: int = Field(..., description="Total number of orders.")
    avg_order_value: float = Field(..., description="Average value per order.")
    avg_delivery_time_days: float = Field(..., description="Average delivery time in days.")
    late_delivery_rate: float = Field(..., description="Ratio of late deliveries.")
    avg_freight_per_order: float = Field(..., description="Average freight cost per order.")
    avg_processing_time_days: float = Field(..., description="Average processing time in days.")
    avg_review_score: float = Field(..., description="Average customer review score.")
    review_count: int = Field(..., description="Total number of reviews.")


class SellerBehaviorInput(BaseModel):
    """Input schema - seller features required for behavior clustering."""

    avg_order_value: float = Field(..., description="Average value per order.")
    avg_delivery_time_days: float = Field(..., description="Average delivery time in days.")
    late_delivery_rate: float = Field(..., description="Ratio of late deliveries.")
    avg_freight_per_order: float = Field(..., description="Average freight cost per order.")
    avg_processing_time_days: float = Field(..., description="Average processing time in days.")
    avg_review_score: float = Field(..., description="Average customer review score.")


class SellerCategoryResponse(BaseModel):
    """Output schema - predicted seller category."""

    cluster_id: int = Field(
        ...,
        description="The assigned cluster ID.",
    )
    segment_name: str = Field(
        ...,
        description="Human-readable segment name.",
    )
